/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package icelaundry;

import java.awt.Color;
// a cha
/**
 *
 * @author X453SA
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.getContentPane().setBackground(new Color(165, 177, 194));
        selfSvc.setBackground(new Color(119, 140, 163));
        kush.setBackground(new Color(119, 140, 163));
        exshit.setBackground(new Color(119, 140, 163));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selfSvc = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kush = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        exshit = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ice Laundry System");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icelaundry/imgsrc/icelond.png"))); // NOI18N

        selfSvc.setPreferredSize(new java.awt.Dimension(148, 149));
        selfSvc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selfSvcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selfSvcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selfSvcMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icelaundry/imgsrc/washer-machine.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Self-Service Checkout");

        javax.swing.GroupLayout selfSvcLayout = new javax.swing.GroupLayout(selfSvc);
        selfSvc.setLayout(selfSvcLayout);
        selfSvcLayout.setHorizontalGroup(
            selfSvcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selfSvcLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selfSvcLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(39, 39, 39))
        );
        selfSvcLayout.setVerticalGroup(
            selfSvcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selfSvcLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        kush.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kushMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kushMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kushMouseExited(evt);
            }
        });
        kush.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kushKeyPressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icelaundry/imgsrc/key.png"))); // NOI18N
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setText("Cashier Mode");
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout kushLayout = new javax.swing.GroupLayout(kush);
        kush.setLayout(kushLayout);
        kushLayout.setHorizontalGroup(
            kushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kushLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(kushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35))
        );
        kushLayout.setVerticalGroup(
            kushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kushLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        exshit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exshit.setPreferredSize(new java.awt.Dimension(148, 149));
        exshit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exshitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exshitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exshitMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icelaundry/imgsrc/exit.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setText("Exit");

        javax.swing.GroupLayout exshitLayout = new javax.swing.GroupLayout(exshit);
        exshit.setLayout(exshitLayout);
        exshitLayout.setHorizontalGroup(
            exshitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exshitLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(exshitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(exshitLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)))
                .addGap(35, 35, 35))
        );
        exshitLayout.setVerticalGroup(
            exshitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exshitLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selfSvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(kush, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exshit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selfSvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kush, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exshit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selfSvcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selfSvcMouseClicked
        this.dispose();
        new selfsvc.selserv1().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_selfSvcMouseClicked

    private void kushKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kushKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_kushKeyPressed
    private void kushNext(){
        this.dispose();
        new kushier.initpwd().setVisible(true);
    }
    private void kushMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kushMouseClicked
        kushNext();
        // TODO add your handling code here:
    }//GEN-LAST:event_kushMouseClicked

    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed
        // TODO add your handling code here:
        kushNext();
    }//GEN-LAST:event_jLabel4KeyPressed

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        kushNext();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5KeyPressed

    private void exshitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exshitMouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_exshitMouseClicked

    private void selfSvcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selfSvcMouseEntered
    selfSvc.setBackground(new Color(209, 216, 224));// TODO add your handling code here:
    }//GEN-LAST:event_selfSvcMouseEntered

    private void kushMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kushMouseEntered
    kush.setBackground(new Color(209, 216, 224));// TODO add your handling code here:
    }//GEN-LAST:event_kushMouseEntered

    private void exshitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exshitMouseEntered
    exshit.setBackground(new Color(209, 216, 224));// TODO add your handling code here:
    }//GEN-LAST:event_exshitMouseEntered

    private void selfSvcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selfSvcMouseExited
    selfSvc.setBackground(new Color(119, 140, 163));
    // TODO add your handling code here:
    }//GEN-LAST:event_selfSvcMouseExited

    private void kushMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kushMouseExited
    kush.setBackground(new Color(119, 140, 163));
    // TODO add your handling code here:
    }//GEN-LAST:event_kushMouseExited

    private void exshitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exshitMouseExited
    exshit.setBackground(new Color(119, 140, 163));// TODO add your handling code here:
    }//GEN-LAST:event_exshitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel exshit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel kush;
    private javax.swing.JPanel selfSvc;
    // End of variables declaration//GEN-END:variables
}
