/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selfsvc;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author X453SA
 */
public class selserv1 extends javax.swing.JFrame {
    int total,Grand,aMass=1,i=1;
    String gitTotal, textAddon1, textAddon2;
    /**
     * Creates new form selserv
     */
    public selserv1() {
        
        initComponents();
        this.getContentPane().setBackground(new Color(236,236,236));
        onePiece();
        oneKG();
        fabric();
        suite();
        mattress();

        goCkout.addActionListener(action);
        
    }
    Action action = new AbstractAction(){
        @Override
        public void actionPerformed(ActionEvent e){
            new checkOut(gitTotal).setVisible(true);
                        
        }
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        goCkout = new javax.swing.JButton();
        goExit = new javax.swing.JButton();
        goReset = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        checkPerfume = new javax.swing.JRadioButton();
        checkFolds = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        showGTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aTable = new javax.swing.JTable();
        oneKg = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        onePiece = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnMattress = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnSuite = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnFabric = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Self-Service");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icelaundry/imgsrc/customer.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Self - Service Checkout");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Choose Preset Services");

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel16.setText("Go to our cashier if you want to have a discount on multiple laundry orders !");

        goCkout.setText("Checkout");

        goExit.setText("Exit");
        goExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goExitActionPerformed(evt);
            }
        });

        goReset.setText("Reset");
        goReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goResetActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Total");

        checkPerfume.setText("Extra Perfume");

        checkFolds.setText("Drapes & Folds");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Rp.");

        showGTotal.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        showGTotal.setText("0");

        aTable.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        aTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Type", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(aTable);

        oneKg.setPreferredSize(new java.awt.Dimension(151, 42));
        oneKg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                oneKgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oneKgMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icelaundry/imgsrc/weight16.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("1 Kilogram Laundry");

        javax.swing.GroupLayout oneKgLayout = new javax.swing.GroupLayout(oneKg);
        oneKg.setLayout(oneKgLayout);
        oneKgLayout.setHorizontalGroup(
            oneKgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oneKgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        oneKgLayout.setVerticalGroup(
            oneKgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oneKgLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(oneKgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        onePiece.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onePieceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onePieceMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icelaundry/imgsrc/shirt.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("1 Piece Laundry");

        javax.swing.GroupLayout onePieceLayout = new javax.swing.GroupLayout(onePiece);
        onePiece.setLayout(onePieceLayout);
        onePieceLayout.setHorizontalGroup(
            onePieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onePieceLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(28, 28, 28))
        );
        onePieceLayout.setVerticalGroup(
            onePieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onePieceLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(onePieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMattress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMattressMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMattressMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icelaundry/imgsrc/double-bed-with-two-pillows.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("Mattress Laundry");

        javax.swing.GroupLayout btnMattressLayout = new javax.swing.GroupLayout(btnMattress);
        btnMattress.setLayout(btnMattressLayout);
        btnMattressLayout.setHorizontalGroup(
            btnMattressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMattressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnMattressLayout.setVerticalGroup(
            btnMattressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMattressLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(btnMattressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnSuite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuiteMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icelaundry/imgsrc/suit.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setText("Suit Laundry");

        javax.swing.GroupLayout btnSuiteLayout = new javax.swing.GroupLayout(btnSuite);
        btnSuite.setLayout(btnSuiteLayout);
        btnSuiteLayout.setHorizontalGroup(
            btnSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSuiteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel11)
                .addGap(25, 25, 25)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSuiteLayout.setVerticalGroup(
            btnSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSuiteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(btnSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnFabric.setPreferredSize(new java.awt.Dimension(151, 42));
        btnFabric.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFabricMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFabricMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icelaundry/imgsrc/fabric (1).png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setText("Special Silk");

        javax.swing.GroupLayout btnFabricLayout = new javax.swing.GroupLayout(btnFabric);
        btnFabric.setLayout(btnFabricLayout);
        btnFabricLayout.setHorizontalGroup(
            btnFabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFabricLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        btnFabricLayout.setVerticalGroup(
            btnFabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFabricLayout.createSequentialGroup()
                .addGroup(btnFabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnFabricLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14))
                    .addGroup(btnFabricLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel13)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(oneKg, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(btnMattress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(onePiece, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSuite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(checkPerfume)
                                .addGap(51, 51, 51)
                                .addComponent(checkFolds))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnFabric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showGTotal))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(goExit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(goReset, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(goCkout, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)))
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(oneKg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onePiece, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMattress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSuite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnFabric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkPerfume)
                            .addComponent(checkFolds))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(showGTotal))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(goExit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goReset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goCkout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goExitActionPerformed
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_goExitActionPerformed

    private void goResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goResetActionPerformed
        total=0;
        Grand = 0;
        checkPerfume.setSelected(false);
        checkFolds.setSelected(false);
        showGTotal.setText("0");
        DefaultTableModel model = (DefaultTableModel) aTable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_goResetActionPerformed

    private void oneKgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneKgMouseEntered
        oneKg.setBackground(new Color(171, 183, 183));// TODO add your handling code here:
    }//GEN-LAST:event_oneKgMouseEntered

    private void oneKgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneKgMouseExited
        oneKg.setBackground(new Color(225, 223, 225));// TODO add your handling code here:
    }//GEN-LAST:event_oneKgMouseExited

    private void onePieceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onePieceMouseEntered
       onePiece.setBackground(new Color(171, 183, 183)); // TODO add your handling code here:
    }//GEN-LAST:event_onePieceMouseEntered

    private void onePieceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onePieceMouseExited
        onePiece.setBackground(new Color(225, 223, 225));        // TODO add your handling code here:
    }//GEN-LAST:event_onePieceMouseExited

    private void btnMattressMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMattressMouseEntered
        btnMattress.setBackground(new Color(171, 183, 183));// TODO add your handling code here:
    }//GEN-LAST:event_btnMattressMouseEntered

    private void btnMattressMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMattressMouseExited
        btnMattress.setBackground(new Color(225, 223, 225));// TODO add your handling code here:
    }//GEN-LAST:event_btnMattressMouseExited

    private void btnSuiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuiteMouseEntered
        btnSuite.setBackground(new Color(171, 183, 183));// TODO add your handling code here:
    }//GEN-LAST:event_btnSuiteMouseEntered

    private void btnSuiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuiteMouseExited
        btnSuite.setBackground(new Color(225, 223, 225));// TODO add your handling code here:
    }//GEN-LAST:event_btnSuiteMouseExited

    private void btnFabricMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFabricMouseEntered
        btnFabric.setBackground(new Color(171, 183, 183));// TODO add your handling code here:
    }//GEN-LAST:event_btnFabricMouseEntered

    private void btnFabricMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFabricMouseExited
        btnFabric.setBackground(new Color(225, 223, 225));// TODO add your handling code here:
    }//GEN-LAST:event_btnFabricMouseExited
    //Start KG Method
    public void checkAddon(){
        //start if statements
        if (checkPerfume.isSelected()){
            total = total + 3000;
            textAddon1 = " With Extra Perfume ";
        }else{
            textAddon1 = "";
            //do nothing and clear the var   
        }
        if (checkFolds.isSelected()){
            total = total + 5000;
            textAddon2 = " With Drapes and Folds ";
        }else{
            textAddon2 = "";
            //do nothing and clear the var
        }
        //end if statements
    }
    public void oneKG(){
        DefaultTableModel model = (DefaultTableModel) aTable.getModel();
        oneKg.addMouseListener(new MouseAdapter (){
            @Override
            public void mouseClicked (MouseEvent e){
                total = 1 * 6000;
                checkAddon();
                Grand = Grand + total;
                gitTotal=String.valueOf(Grand);
                showGTotal.setText(gitTotal);
                model.addRow(new Object[]{i, "1 Kilo Laundry" + textAddon1 + textAddon2,aMass + "KG/PCS", "Rp. " + total});
                i=i+1;
            }
        });
        
    }
    public void onePiece(){
        DefaultTableModel model = (DefaultTableModel) aTable.getModel();
        onePiece.addMouseListener(new MouseAdapter (){
            @Override
            public void mouseClicked(MouseEvent e){
                total = 4000;
                checkAddon();
               
                Grand = Grand + total;
                gitTotal=String.valueOf(Grand);
                showGTotal.setText(gitTotal);
                model.addRow(new Object[]{i, "1 Piece Laundry" + textAddon1 + textAddon2,aMass + "KG/PCS", "Rp. " + total});
                i=i+1;
            }
        });
    }
    public void mattress(){
        DefaultTableModel model = (DefaultTableModel) aTable.getModel();
        btnMattress.addMouseListener(new MouseAdapter (){
            @Override
            public void mouseClicked(MouseEvent e){
                total = 35000;
                checkAddon();
                
                Grand = Grand + total;
                gitTotal=String.valueOf(Grand);
                showGTotal.setText(gitTotal);
                model.addRow(new Object[]{i, "Mattress Laundry" + textAddon1 + textAddon2,aMass + "KG/PCS", "Rp. " + total});
                i=i+1;
            }
        });
    }
    public void suite(){
        DefaultTableModel model = (DefaultTableModel) aTable.getModel();
        btnSuite.addMouseListener(new MouseAdapter (){
            @Override
            public void mouseClicked(MouseEvent e){
                total = 12000;
                checkAddon();
                
                Grand = Grand + total;
                gitTotal=String.valueOf(Grand);
                showGTotal.setText(gitTotal);
                model.addRow(new Object[]{i, "Suite Laundry" + textAddon1 + textAddon2,aMass + "KG/PCS", "Rp. " + total});
                i=i+1;
            }
        });
    }
    public void fabric(){
        DefaultTableModel model = (DefaultTableModel) aTable.getModel();
        btnFabric.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                total = 10000;
                checkAddon();
               
                Grand = Grand + total;
                gitTotal=String.valueOf(Grand);
                showGTotal.setText(gitTotal);
                model.addRow(new Object[]{i, "Special Silk Laundry" + textAddon1 + textAddon2,aMass + "KG/PCS", "Rp. " + total});
                i=i+1;
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selserv1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selserv1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selserv1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selserv1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selserv1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable aTable;
    private javax.swing.JPanel btnFabric;
    private javax.swing.JPanel btnMattress;
    private javax.swing.JPanel btnSuite;
    private javax.swing.JRadioButton checkFolds;
    private javax.swing.JRadioButton checkPerfume;
    private javax.swing.JButton goCkout;
    private javax.swing.JButton goExit;
    private javax.swing.JButton goReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel oneKg;
    private javax.swing.JPanel onePiece;
    public javax.swing.JLabel showGTotal;
    // End of variables declaration//GEN-END:variables
}
